#!/usr/bin/env bash

# Identical to __set_default_globals, but won't actually run
my_globals () {
    # We set global variables here

    #butter_version is set in butter
    butter_root="/mnt/butter"
    butter_prop_prefix="user.be.popho.butter"
    default_max_snapshots="5"
    default_rm_snapshots="1"

    if [[ -r /etc/machine-id ]]; then
        butter_host="$(< /etc/machine-id)"
    else
        butter_host="$(uname -n)"
    fi

    declare -ga butter_prop_array
    butter_prop_array=('mountpoint'
                       'mountpoints.managed.*'
                       'custom.*'
                       'snapshot.*'
                       'version'
                       'uuid')

}

# Uncomment the following line for your changes to take effect
#my_globals
