#!/usr/bin/env bash

# Original Author: Moviuro
# Distributed under the terms of the WTFPL.
#
# You can find a full copy of the license here:
#      http://www.wtfpl.net/txt/copying/

# Set to debug mode
if [[ "$1" == "-d" ]] || [[ "$1" == "--debug" ]]; then
    set -x
    shift
fi

butter_version="butter v10"
pid=$$

# Print version and exit
if [[ "$1" == "version" ]] || [[ "$1" == "--version" ]]; then
    printf "%s\n" "$butter_version"
    exit 0
fi

# Find libs
[[ -d ./lib-btr && -r ./lib-btr ]] && _lib_dir="./lib-btr"
[[ -d /usr/lib/butter && -r /usr/lib/butter ]] && _lib_dir="/usr/lib/butter"
[[ -d /usr/local/lib/butter && -r /usr/local/lib/butter ]] &&
  _lib_dir="/usr/local/lib/butter"

# If libs are not found, fail
if [[ -z "$_lib_dir" ]] ; then
    printf "%s\n" "butter libs were not found, aborting..."
    exit 1
fi

shopt -s nullglob

for _lib in $_lib_dir/*; do
    . $_lib
done

__run "$@"

