#!/usr/bin/env bash

__run () {
    # TODO: change logic: all commands don't require the mountpoints etc.
    __init

    __parse_cmd "$@"
}

__parse_cmd () {
    case "$1" in
        bootstrap)
            shift
            __require_root
            __cmd_bootstrap "$@"
            exit ;;
        create)
            shift
            __require_root
            __cmd_create "$@"
            exit ;;
        destroy)
            shift
            __require_root
            __cmd_destroy "$@"
            exit ;;
        snapshot)
            shift
            __require_root
            __cmd_snapshot "$@"
            exit ;;
        snapremove)
            shift
            __require_root
            __cmd_snapremove "$@"
            exit ;;
        set)
            shift
            __require_root
            __cmd_set "$@"
            exit ;;
        get)
            shift
            __cmd_get "$@"
            exit ;;
        help)
            shift
            __cmd_help
            exit ;;
        *)
            shift
            __cmd_help >&2
            exit 1 ;;
    esac
}

__cmd_create () {
    local _mountpoint _escaped_name _path

    _mountpoint="$1"
    _escaped_name="$(__escape "$_mountpoint")"
    _path="$butter_host"/"$_escaped_name"

    __require_bootstrapped
    btrfs subvolume create "$butter_root/$_path"
    __set_one_prop "mountpoint" "$_mountpoint" "$_path"
}

__cmd_destroy () {
    :
}

__cmd_snapshot () {
    :
}

__cmd_snapremove () {
    :
}

__cmd_set () {
    local _prop _value _mountpoint _path _new_path

    _prop="$1"
    _value="$2"
    _mountpoint="$3"
    _path="$(__find_path "$_mountpoint")"

    __require_bootstrapped

    # We move the mountpoint
    if [[ "$_prop" == "mountpoint" ]]; then
        _new_path="$butter_root/$butter_host/$(__escape "$_value")"
        if [[ -a "$_new_path" ]]; then
            __fatal "$_new_path already exists, can't move $_path"
        fi
        mv "$_path" "$_new_path"
        _path="$_new_path"
    fi
    __set "$butter_prop_prefix.$_prop" "$_value" "$_path"
}

__cmd_get () {
    local _prop _mountpoint

    _prop="$1"
    _mountpoint="$2"
    _path="$(__find_path "$_mountpoint")"

    __require_bootstrapped
    __require_in_props "$_prop"
    __get "$butter_prop_prefix.$_prop" "$_path"

}

__cmd_help () {
    __print_help
}

__cmd_bootstrap () {
    __info "butter root is $butter_root"
    __bootstrap
    __require_bootstrapped
}

__require_root () {
    [[ -w "$butter_root" ]] || __fatal "Can't write to $butter_root"
}
