#!/usr/bin/env bash

__set_default_globals () {
    # We set global variables here

    #butter_version is set in butter
    butter_root="/mnt/butter"
    butter_prop_prefix="user.be.popho.butter"
    default_max_snapshots="5"
    default_rm_snapshots="1"

    if [[ -r /etc/machine-id ]]; then
        butter_host="$(< /etc/machine-id)"
    else
        butter_host="$(uname -n)"
    fi

    declare -ga butter_prop_array
    butter_prop_array=('mountpoint'
                       'mountpoints.managed.*'
                       'custom.*'
                       'snapshot.*'
                       'version'
                       'uuid'
                       'host')
}

__set_globals () {
    # Load default globals
    __set_default_globals

    # Override them if needed
    if [[ -r /etc/butterrc ]]; then
        . /etc/butterrc
    fi
}
