#!/usr/bin/env bash

__set_default_globals () {
    # We set global variables here

    #butter_version is set in butter
    butter_root="/mnt/butter"
    butter_prop_prefix="user.be.popho.butter"

    if [[ -r /etc/machine-id ]]; then
        butter_host="$(< /etc/machine-id)"
    else
        butter_host="$(uname -n)"
        __info "Could not find /etc/machine-id: we use $butter_host as hostname"
    fi

    declare -ga butter_prop_array
    butter_prop_array=('mountpoint'
                       'version')
}

__set_globals () {
    # Load default globals
    __set_default_globals

    # Override them if needed
    if [[ -r /etc/butterrc ]]; then
        . /etc/butterrc
    fi
}
