#!/usr/bin/env bash

__print_help () {
cat << __EOH__
NAME
    $0 is a btrfs sinapshot manager.

SYNOPSIS
    $0 add MOUNTPOINT[,...] [TYPE]
    $0 bootstrap
    $0 create MOUNTPOINT [PROP VALUE [...]]
    $0 destroy MOUNTPOINT
    $0 list
    $0 remove MOUNTPOINT [TYPE]
    $0 snaplist
    $0 snapshot MOUNTPOINT[,...]|ALL [PROP VALUE [...]]
    $0 snapremove MOUNTPOINT[,...] [COUNT [PROP VALUE [...]]]
    $0 set MOUNTPOINT[,...] PROP VALUE [...]
    $0 get [-H] [-o values] MOUNTPOINT[,...] PROP [PROP [...]]
    $0 help
    $0 find [PROP VALUE [...]]

DESCRIPTION
    $0 manages snapshots and retention, while making extensive use of extended
    attributes.

    $0 add MOUNTPOINT [TYPE]

        Adds a mountpoint to the default settings for a given type of snapshot.
        See also $0 remove.

        Example:

        After issuing the following command, \`$0 snapshot ALL type hourly\` will
        snapshot /, /home and /var too.
          # $0 add /,/home,/var hourly

    $0 bootstrap

        Tells you what to do to get started.  Will certainly get dropped.

        Typically, you should do this first:
          # mkdir -p /mnt/butter
          # mount -osubvol=/ /mnt/butter
          # mkdir -p $butter_root/$butter_host

    $0 create MOUNTPOINT [PROP VALUE [...]]

        Will create a btrfs(8) subvolume in the $0 root and set some initial
        values, as well as default values for the following properties:

          o mountpoint (obviously)
          o snapshot.default.max (defaults to 5)
          o uuid
          o snapshot.is (must be "0")

        Examples:

          # $0 create / snapshot.hourly.max 24 snapshot.daily.max 7
          # $0 create /home snapshot.default.max 10

    $0 destroy MOUNTPOINT

        Will delete all subvolumes that have the given mountpoint (snapshots
        too) that live under the $0 root

        Example:

          # $0 destroy /var

    $0 list

        Lists all associations between a snapshot type and mountpoints.
        It is useful to use it before issuing a snapshot command to "ALL".

        Example:

          # $0 list
          TYPE     MOUNTPOINT
          daily    /
          daily    /home
          daily    /var
          default  /var
          default  /

    $0 remove MOUNTPOINT[,...] [TYPE]

        Removes a mountpoint from the default list for a given snapshot type.
        See also $0 add.

        Example:
          # $0 remove /var yearly

    $0 snaplist

        Lists all snapshots.  Does not show subvolumes.

    $0 snapshot MOUNTPOINT|ALL [PROP VALUE [...]]

        Take a snapshot and set some properties, as well as some default values
        for the following properties:

          o snapshot.type (defaults to "default")
          o snapshot.is (must be "1")
          o snapshot.timestamp
          o uuid

        Examples:

        Snapshot /var/log with type "manual" and a comment
          # $0 snapshot /var/log type manual comment "first shot at $0"

        Simply snapshot /home
          # $0 snapshot /home

        Snapshot all subvolumes that must (see $0 add) for a given type:
          # $0 snapshot ALL type daily

    $0 snapremove MOUNTPOINT [COUNT [PROP VALUE [...]]]

        Removes a number of old snapshots, given some conditions.
        COUNT defaults to "5".
        snapremove will delete the snpashots with the smallest
        snapshot.timestamp values first.

        Examples:

        Remove the 2 oldest snapshots of /
          # $0 snapremove / 2

        Remove the 5 oldest "hourly" snapshots of / and /home (10 total)
          # $0 snapremove /,/home 5 snapshot.type hourly

    $0 set MOUNTPOINT PROP VALUE [...]

        Set some properties.
        The submitted properties must be validated by $0
        Arbitrary properties can be set with the "custom." prefix.
        Some properties are read-only and you should not attempt to modify
        them, such as:

          o snapshot.is
          o mountpoint
          o uuid

        Example:

        Set the default maximum number of snapshots for /var/log
          # $0 set /var/log snapshot.default.max 3

    $0 get [-H] [-o values] MOUNTPOINT PROP [PROP [...]]

        Get some properties in a nice table.

        Options:

          o -H: suppress headers
          o -o values: only print values

        Example:

          # $0 get / uuid snapshot.default.max
          # $0 get -H /var/log snapshot.daily.max

    $0 help

        Display this help text

    $0 find [PROP VALUE [...]]

        Find snapshots or subvolumes that match PROP=VALUE for submitted
        properties and values.

        Example:

        Find snapshots with type "foo"
          # $0 find snapshot.is 1 snapshot.type foo

__EOH__
}
