#!/usr/bin/env bash

__print_help () {
cat << __EOH__
NAME
    butter is a btrfs snapshot manager.

SYNOPSIS
    butter [-d] add MOUNTPOINT[,...] [TYPE]
    butter [-d] bootstrap
    butter [-d] create MOUNTPOINT [PROP VALUE [...]]
    butter [-d] destroy MOUNTPOINT
    butter [-d] list
    butter [-d] remove MOUNTPOINT [TYPE]
    butter [-d] snaplist
    butter [-d] snapshot MOUNTPOINT[,...]|ALL [PROP VALUE [...]]
    butter [-d] snapremove MOUNTPOINT[,...] [COUNT [PROP VALUE [...]]]
    butter [-d] set MOUNTPOINT[,...] PROP VALUE [...]
    butter [-d] get [-H] [-o values] MOUNTPOINT[,...] PROP [PROP [...]]
    butter [-d] help
    butter [-d] find [PROP VALUE [...]]

DESCRIPTION
    butter manages snapshots and retention, while making extensive use of extended
    attributes.

    butter -d [COMMAND [ARGS...]]

        Run butter in debug mode (bash(1)'s set -x)

    butter add MOUNTPOINT [TYPE]

        Adds a mountpoint to the default settings for a given type of snapshot.
        See also butter remove.

        Example:

        After issuing the following command,
          # butter add /,/home,/var hourly
        This next command will snapshot /, /home and /var
          # butter snapshot ALL type hourly

    butter bootstrap

        Tells you what to do to get started.  Will certainly get dropped.

        Typically, you should do this first:
          # mkdir -p \$butter_root
          # mount -osubvol=/ \$butter_root
          # mkdir -p \$butter_root/\$butter_host

        Default values are:
          o \$butter_root=/mnt/butter
          o \$butter_host=\$(\< /etc/machine-id) with systemd
          o \$butter_host=\$(uname -n) without systemd

    butter create MOUNTPOINT [PROP VALUE [...]]

        Will create a btrfs(8) subvolume in the butter root and set some initial
        values, as well as default values for the following properties:

          o mountpoint (obviously)
          o snapshot.default.max (defaults to 5)
          o uuid
          o snapshot.is (must be "0")

        The subvolume will be created inside the butter root and will not be
        mounted.

        Examples:

          # butter create / snapshot.hourly.max 24 snapshot.daily.max 7
          # butter create /home snapshot.default.max 10

    butter destroy MOUNTPOINT

        Will delete all subvolumes that have the given mountpoint (snapshots
        too) that live under the butter root

        Example:

          # butter destroy /var

    butter snapconfig

        Shows snapshot type and mountpoints configuration, created using add
        and remove.
        It is useful to use it before issuing a snapshot command to "ALL".

        Example:

          # butter snapconfig
          TYPE     MOUNTPOINT
          daily    /
          daily    /home
          daily    /var
          default  /var
          default  /

    butter remove MOUNTPOINT[,...] [TYPE]

        Removes a mountpoint from the default list for a given snapshot type.
        See also butter add.

        Example:
          # butter remove /var yearly

    butter snaplist

        Lists all snapshots.  Does not show subvolumes.

    butter snapshot MOUNTPOINT|ALL [PROP VALUE [...]]

        Take a snapshot and set some properties, as well as some default values
        for the following properties:

          o snapshot.type (defaults to "default")
          o snapshot.is (must be "1")
          o snapshot.timestamp
          o uuid

        Examples:

        Snapshot /var/log with type "manual" and a comment
          # butter snapshot /var/log type manual comment "first shot at butter"

        Simply snapshot /home
          # butter snapshot /home

        Snapshot all subvolumes that must (see butter add) for a given type:
          # butter snapshot ALL type daily

    butter snapremove MOUNTPOINT [COUNT [PROP VALUE [...]]]

        Removes a number of old snapshots, given some conditions.
        COUNT defaults to "5".
        snapremove will delete the snpashots with the smallest
        snapshot.timestamp values first.

        Examples:

        Remove the 2 oldest snapshots of /
          # butter snapremove / 2

        Remove the 5 oldest "hourly" snapshots of / and /home (10 total)
          # butter snapremove /,/home 5 snapshot.type hourly

    butter set MOUNTPOINT PROP VALUE [...]

        Set some properties.
        The submitted properties must be validated by butter
        Arbitrary properties can be set with the "custom." prefix.
        Some properties are read-only and you should not attempt to modify
        them, such as:

          o snapshot.is
          o mountpoint
          o uuid

        Example:

        Set the default maximum number of snapshots for /var/log
          # butter set /var/log snapshot.default.max 3

    butter get [-H] [-o values] MOUNTPOINT PROP [PROP [...]]

        Get some properties in a nice table.

        Options:

          o -H: suppress headers
          o -o values: only print values

        Example:

          # butter get / uuid snapshot.default.max
          # butter get -H /var/log snapshot.daily.max

    butter help

        Display this help text

    butter find [PROP VALUE [...]]

        Find snapshots or subvolumes that match PROP=VALUE for submitted
        properties and values.

        Example:

        Find snapshots with type "foo"
          # butter find snapshot.is 1 snapshot.type foo

__EOH__
}
