#!/usr/bin/env bash

__init () {
    # We set global variables first
    __set_globals

    # Is the root mounted?
    if ! findmnt $butter_root >/dev/null 2>&1; then
        __fatal "$butter_root is not mounted"
    fi

    # We check that the root has the same prog version as the current butter
    # If not, then force update of properties
    if __has_root_priv; then
        __check_version || __update
    fi
}

__check_version () {
    local _current

    _current="$(__get_one_prop "version" "$butter_root/$butter_host")"
    [[ "$_current" == "$butter_version" ]]
}

__update () {
    __require_root_priv
    # We update the properties of the root
    __set_one_prop "version" "$butter_version" "$butter_root/$butter_host"
    # We update the properties of the managed sub-volumes
    # ...
}

