#!/usr/bin/env bash

__fatal () {
    printf '%s\n!! %s\n' "Fatal error" "$1"
    exit 2
}

__info () {
    printf '%s\nII %s\n' "Information" "$1"
}

__get () {
    getfattr --only-values --name "$1" "$2" 2>/dev/null
}

__set () {
    setfattr --name "$1" --value "$2" "$3"
}

__get_one_prop () {
    local _prop _path

    _prop="$1"
    _path="$2"

    __require_in_props "$_prop"
    __get "$butter_prop_prefix"."$_prop" "$butter_root"/"$_path"
}

__set_one_prop () {
    local _prop _value _path

    _prop="$1"
    _value="$2"
    _path="$3"

    __require_in_props "$_prop"
    __set "$butter_prop_prefix"."$_prop" "$_value" "$butter_root"/"$_path"
}

__is_in_array () {
    local _found _prop _array _item

    _found=0
    _prop="$1"
    _array="$2"

    for _item in "${_array[*]}"; do
        if [[ "$_item" == "$_prop" ]]; then
            _found=1
            continue
        fi
    done

    (( $_found ))
}

__require_in_props () {
    local _prop

    _prop="$1"

    __is_in_array "$_prop" "$butter_prop_array"
}
